select_origin: directory
files_origin: "/Users/tom/Documents/fichesalgoJ"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: "/Users/tom/Documents/cosma-e3d/export/"
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#a7a0a0"
    stroke: "#a7a0a0"
  algorithme:
    fill: "#6a4c93"
    stroke: "#6a4c93"
  concept:
    fill: "#1982c4"
    stroke: "#1982c4"
  professionnel:
    fill: "#ff8e38"
    stroke: "#ff8e38"
  techniques:
    fill: "#8ac927"
    stroke: "#8ac927"
  méthodes:
    fill: "#59cf92"
    stroke: "#59cf92"
  investigations:
    fill: "#ef1f1f"
    stroke: "#ef1f1f"
  organisation:
    fill: "#f36d9c"
    stroke: "#f36d9c"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
  o:
    stroke: simple
    color: "#e01f1f"
  g:
    stroke: simple
    color: "#000000"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 6
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 10
node_size_min: 2
attraction_force: 75
attraction_distance_max: 250
attraction_vertical: 0.1
attraction_horizontal: 0.1
views: {}
chronological_record_meta: created
css_custom: "/Users/tom/Documents/cosma-e3d/themes/algoj.css"
record_metas: []
title: "AlgoJ"
author: ""
description: ""
keywords: []
link_symbol: →
devtools: false
lang: fr
